language: node_js

node_js:
- 4.4.5

branches:
  only:
    - master

before_install:
# Decrypt the private key
- openssl aes-256-cbc -K $encrypted_af62f0936c1a_key -iv $encrypted_af62f0936c1a_iv
  -in mountainside_id_rsa.enc -out ~\/.ssh/mountainside_id_rsa -d
# Set the permission of the key
- chmod 600 ~/.ssh/mountainside_id_rsa
# Start SSH agent
- eval $(ssh-agent)
# Add the private key to the system
- ssh-add ~/.ssh/mountainside_id_rsa
# Copy SSH config
- cp .travis/ssh_config ~/.ssh/config
# Set Git config
- git config --global user.name "keller07"
- git config --global user.email "keller.rd@foxmail.com"

install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
