language: node_js
node_js:
- 4.4.5
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_ebbad52ff68d_key -iv $encrypted_ebbad52ff68d_iv
  -in .travis/mountainside_id_rsa.enc -out ~\/.ssh/mountainside_id_rsa -d
- chmod 600 ~/.ssh/mountainside_site_id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/mountainside_site_id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "keller07"
- git config --global user.email "keller.rd@foxmail.com"
install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
